### ISSUE TITLE
cmake cannot find nvidia hpc sdk mpi (openmpi)

### ISSUE THREAD

**Issue by cwsmith** [ornladios/ADIOS2#2595]
Installing adios2 2.7.0 (and 2.6.0) via spack (develop @ fcf99be) with the spec `adios2@2.7.0 ~sst +fortran` fails during the cmake call to `FindMPI`.

The SDKs MPI provides `mpicc`, `mpicxx`, etc. as symlinks to an `env.sh` script:

```
$ lss /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/comm_libs/mpi/bin/
total 16
-rwxr-xr-x 1 root root  270 Dec  3 19:33 env.sh
...
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpif90 -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpif77 -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpiexec -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpicxx -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpiCC -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpicc -> env.sh
lrwxrwxrwx 1 root root    6 Jan 12 13:56 mpic++ -> env.sh
...
```

Where `env.sh` sets some environment variables and then calls the binary in the hidden `.bin` dir:

```
$ cat /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/comm_libs/mpi/bin/env.sh 
#!/bin/bash

EXE=$(basename $0)

MY_PATH=$(readlink -f $0)
MY_DIR=$(dirname $MY_PATH)
OMPI_ROOT=$(readlink -f $MY_DIR/..)
export OPAL_PREFIX=$OMPI_ROOT

# for -Mscalapack
export MPILIBNAME=openmpi
export MPILIBVER=3.1.5
export MPIDIR=$OMPI_ROOT

$MY_DIR/.bin/$EXE "$@"
```

The CMake log is attached.
[adios2_cmakeFail.log](https://github.com/ornladios/ADIOS2/files/5851781/adios2_cmakeFail.log)

**To Reproduce**
I don't have a minimal reproducer at this point.

**Expected behavior**
Find the mpi install and finish running cmake successfully.

**Desktop (please complete the following information):**
 - OS/Platform: [RPI AiMOS (mini Summit)](https://secure.cci.rpi.edu/wiki/clusters/DCS_Supercomputer/), RHEL7
 - Compiler: nvhpc 20.11

**Comment by cwsmith** [comment]
CMake completes successfully when running it outside of spack with the following cmake command:

```
cmake3 $1 \
-DCMAKE_INSTALL_PREFIX:STRING=$PWD/install \
'-DCMAKE_BUILD_TYPE:STRING=Release' \
'-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' \
'-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' \
'-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' \
'-DCMAKE_INSTALL_RPATH:STRING=<....> \
'-DCMAKE_PREFIX_PATH:STRING=<....> \
'-DBUILD_SHARED_LIBS:BOOL=ON' \
'-DADIOS2_BUILD_TESTING=OFF' \
'-DADIOS2_BUILD_EXAMPLES=OFF' \
'-DADIOS2_USE_MPI=ON' \
'-DADIOS2_USE_MGARD=OFF' \
'-DADIOS2_USE_ZFP=ON' \
'-DADIOS2_USE_SZ=ON' \
'-DADIOS2_USE_DataMan=OFF' \
'-DADIOS2_USE_SST=OFF' \
'-DADIOS2_USE_HDF5=OFF' \
'-DADIOS2_USE_Python=OFF' \
'-DADIOS2_USE_Fortran=ON' \
'-DADIOS2_USE_Endian_Reverse=OFF' \
'-DBUILD_TESTING:BOOL=OFF' \
'-DADIOS2_USE_Blosc=ON' \
'-DADIOS2_USE_BZip2=ON' \
'-DADIOS2_USE_PNG=ON' \
'-DADIOS2_USE_SSC=ON' \
'-DADIOS2_USE_DataSpaces=OFF' \
'-DADIOS2_USE_IME=OFF' 

```

**Comment by williamfgc** [comment]
@cwsmith I wonder if it's a conflict between spack, CMake and `/opt` installed mpi from your log (thanks for providing it BTW). I don't know if [configuring spack](https://spack.readthedocs.io/en/latest/configuration.html#configuration-files) would make any difference. Thanks for reporting this, seems like an error on spack adios2 configuration, not the library.

**Comment by cwsmith** [comment]
Hi @williamfgc.  You're welcome.  Thanks for taking a look and the feedback.  

I'm attempting to install adios2 within a [spack environment](https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html).  All the adios2 deps (with `sst` disabled) installed without issue but I didn't check if adios2 is the only package that depends on MPI.  I'll look into that and will post my `spack.yaml` shortly.

**Comment by williamfgc** [comment]
@cwsmith you're welcome. Please feel free to follow up as we also help maintain the [spack adios2 package configuration](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/adios2/package.py) .

> check if adios2 is the only package that depends on MPI

Without sst only HDF5 depends depends on MPI, but should be [OFF by default](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/adios2/package.py#L62). Hope this helps.

**Comment by cwsmith** [comment]
Thanks @williamfgc.  I'll try installing a simple package that depends on mpi to see if spack is correctly using the nvhpc openmpi install.

For the record, the self contained `spack.yaml` (the environment does not depend on any non-default yaml other files) used for the failed install is below.  

```
spack:
  config:
    install_tree: /gpfs/u/barn/MPFS/MPFSsmth/wdmapp/wdmapp-deps-nvhpc
    module_roots:
      lmod: /gpfs/u/barn/MPFS/MPFSsmth/wdmapp/wdmapp-deps-nvhpc/lmod
    concretization: together
  repos:
  - /gpfs/u/barn/MPFS/MPFSsmth/wdmapp/wdmapp-config/spack/wdmapp/
  mirrors:
    wdmSources: file:///gpfs/u/home/MPFS/MPFSsmth/barn/wdmapp/spack-mirror-21-01-21
  view: false
  specs:
  - openmpi
  - cmake
  - pspline
  - adios2@2.7.0 +fortran ~sst
  packages:
    all:
      compiler: [nvhpc@20.11, gcc@8.4.0]
      providers:
        mpi: [openmpi@3.1.5]
      version: []
      target: []
      buildable: true
    openmpi:
      externals:
      - spec: openmpi@3.1.5
        prefix: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/comm_libs/mpi/
      target: []
      compiler: []
      buildable: false
      providers: {}
      version: []
    cmake:
      externals:
      - spec: cmake@3.18.4
        prefix: /gpfs/u/software/dcs-spack-install/vDev1b33008_1/linux-rhel7-power9le/gcc-8.4.0/cmake-3.18.4-vsxvprd6nhbwhlvjb23bumekhbc2bpd6/
      target: []
      compiler: []
      buildable: true
      providers: {}
      version: []
    cuda:
      externals:
      - spec: cuda@11.1
        prefix: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/cuda/11.1/
      version: []
      target: []
      compiler: []
      buildable: false
      providers: {}
    slurm:
      externals:
      - spec: slurm@system
        prefix: /usr
      version: []
      target: []
      compiler: []
      buildable: false
      providers: {}
  compilers:
  - compiler:
      spec: nvhpc@20.11
      paths:
        cc: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/compilers/bin/nvc
        cxx: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/compilers/bin/nvc++
        f77: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/compilers/bin/nvfortran
        fc: /opt/nvidia/hpc_sdk/Linux_ppc64le/20.11/compilers/bin/nvfortran
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: [/opt/nvidia/hpc_sdk/modulefiles/nvhpc/20.11]
      environment: {unset: []}
      extra_rpaths: []
  - compiler:
      spec: gcc@8.4.0
      paths:
        cc: /gpfs/u/software/ppc64le-rhel7/gcc/8.4.0/1/bin/gcc
        cxx: /gpfs/u/software/ppc64le-rhel7/gcc/8.4.0/1/bin/g++
        f77: /gpfs/u/software/ppc64le-rhel7/gcc/8.4.0/1/bin/gfortran
        fc: /gpfs/u/software/ppc64le-rhel7/gcc/8.4.0/1/bin/gfortran
      flags: {}
      operating_system: rhel7
      target: ppc64le
      modules: []
      environment: {unset: []}
      extra_rpaths: []
```
